<#
.SYNOPSIS
  VaxPlan Android Release APK Build Script (signed for distribution)

.DESCRIPTION
  Builds a signed release APK suitable for Google Play Store or direct sideload.
  Requires a signing keystore. On first run, generates a new keystore if none exists.
  Modified to use safe ASCII characters to prevent byte parsing corruption under standard Windows PowerShell.
  
  SECURITY: Never commit the keystore file or passwords to source control.

.PARAMETER KeystorePath
  Path to the JKS keystore file. Default: .\android-release.keystore

.PARAMETER KeyAlias
  Alias of the key within the keystore. Default: vaxplan-release

.EXAMPLE
  .\scripts\Build-Android-Release.ps1
  .\scripts\Build-Android-Release.ps1 -KeystorePath "C:\secure\vaxplan.jks" -KeyAlias "vaxplan"
#>

param(
  [string]$KeystorePath = "android-release.keystore",
  [string]$KeyAlias = "vaxplan-release"
)

$ErrorActionPreference = "Stop"

Write-Host ""
Write-Host "======================================================" -ForegroundColor Cyan
Write-Host "  VaxPlan  Android APK Builder (Release / Signed)" -ForegroundColor Cyan
Write-Host "======================================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "  [WARN] IMPORTANT: Keep your keystore file secure!" -ForegroundColor Yellow
Write-Host "     If you lose it, you CANNOT update your Play Store listing." -ForegroundColor Yellow
Write-Host ""

# -- 1. Keystore setup -----------------------------------------------------
if (-not (Test-Path $KeystorePath)) {
  Write-Host "> No keystore found. Generating a new one..." -ForegroundColor Yellow
  Write-Host "  You will be prompted to set a password and organizational details." -ForegroundColor Cyan
  Write-Host ""
  
  keytool -genkeypair `
    -v `
    -keystore $KeystorePath `
    -alias $KeyAlias `
    -keyalg RSA `
    -keysize 2048 `
    -validity 10000 `
    -dname "CN=VaxPlan, OU=Health, O=Ministry of Health, L=Lusaka, ST=Lusaka, C=ZM"
  
  if ($LASTEXITCODE -ne 0) { Write-Error "keytool failed — ensure Java JDK is installed"; exit 1 }
  Write-Host ""
  Write-Host "  [OK] Keystore generated: $KeystorePath" -ForegroundColor Green
  Write-Host "  [WARN] Back this file up securely before proceeding!" -ForegroundColor Yellow
  Write-Host ""
}

# -- 2. Read passwords securely --------------------------------------------
$storePass = Read-Host "Enter keystore password" -AsSecureString
$keyPass   = Read-Host "Enter key password (Enter for same as keystore)" -AsSecureString

$storePwd = [Runtime.InteropServices.Marshal]::PtrToStringAuto(
  [Runtime.InteropServices.Marshal]::SecureStringToBSTR($storePass))
$keyPwd = [Runtime.InteropServices.Marshal]::PtrToStringAuto(
  [Runtime.InteropServices.Marshal]::SecureStringToBSTR($keyPass))
if ([string]::IsNullOrEmpty($keyPwd)) { $keyPwd = $storePwd }

# -- 3. Build Vite bundle --------------------------------------------------
Write-Host ""
Write-Host "> Building Vite production bundle..." -ForegroundColor Yellow
npm run build
if ($LASTEXITCODE -ne 0) { Write-Error "Vite build failed"; exit 1 }
Write-Host "  [OK] Build complete" -ForegroundColor Green

# -- 4. Capacitor sync ----------------------------------------------------
Write-Host ""
Write-Host "> Syncing to Android project..." -ForegroundColor Yellow
npx cap sync android
if ($LASTEXITCODE -ne 0) { Write-Error "cap sync failed"; exit 1 }
Write-Host "  [OK] Sync complete" -ForegroundColor Green

# -- 5. Write signing config into local.properties ------------------------
$absKeystore = (Resolve-Path $KeystorePath).Path.Replace("\", "/")
$localProps = "android\local.properties"
$signingBlock = @"

## VaxPlan signing config (auto-generated by Build-Android-Release.ps1)
## DO NOT COMMIT local.properties to source control
storeFile=$absKeystore
storePassword=$storePwd
keyAlias=$KeyAlias
keyPassword=$keyPwd
"@
Add-Content -Path $localProps -Value $signingBlock

# -- 6. Build release APK -------------------------------------------------
Write-Host ""
Write-Host "> Building release APK..." -ForegroundColor Yellow
Push-Location android
.\gradlew.bat assembleRelease
if ($LASTEXITCODE -ne 0) { Pop-Location; Write-Error "Gradle release build failed"; exit 1 }
Pop-Location

# -- 7. Clean up passwords from local.properties --------------------------
$content = Get-Content $localProps | Where-Object { $_ -notmatch "storePassword|keyPassword" }
Set-Content $localProps $content

$apkPath = "android\app\build\outputs\apk\release\app-release.apk"
if (Test-Path $apkPath) {
  $apkSize = [math]::Round((Get-Item $apkPath).Length / 1MB, 1)
  Write-Host ""
  Write-Host "======================================================" -ForegroundColor Green
  Write-Host "  [OK] Signed release APK built!" -ForegroundColor Green
  Write-Host "  [FILE] $apkPath (${apkSize} MB)" -ForegroundColor Green
  Write-Host ""
  Write-Host "  Next steps:" -ForegroundColor Cyan
  Write-Host "  * Sideload: adb install $apkPath" -ForegroundColor White
  Write-Host "  * Play Store: upload to Google Play Console" -ForegroundColor White
  Write-Host "======================================================" -ForegroundColor Green
}
