import { db } from "../server/db";
import { sql } from "drizzle-orm";
import {
  provinces,
  districts,
  facilities,
  villages,
  populationData,
} from "../shared/schema";

async function seedDatabase() {
  console.log("Seeding database with sample data for Papua New Guinea...");
  console.log("This script is idempotent - safe to run multiple times.");

  try {
    await db.transaction(async (tx) => {
      console.log("\nClearing existing seed data...");
      await tx.execute(sql`DELETE FROM population_data`);
      await tx.execute(sql`DELETE FROM session_villages`);
      await tx.execute(sql`DELETE FROM vaccine_requirements`);
      await tx.execute(sql`DELETE FROM budget_items`);
      await tx.execute(sql`DELETE FROM session_plans`);
      await tx.execute(sql`DELETE FROM mobilization_activities`);
      await tx.execute(sql`DELETE FROM htr_scores`);
      await tx.execute(sql`DELETE FROM villages`);
      await tx.execute(sql`DELETE FROM facilities`);
      await tx.execute(sql`DELETE FROM districts`);
      await tx.execute(sql`DELETE FROM provinces`);
      console.log("Cleared existing data.");

      const insertedProvinces = await tx
        .insert(provinces)
        .values([
          { name: "Central Province", code: "CPL", region: "Papua" },
          { name: "Eastern Highlands Province", code: "EHP", region: "Highlands" },
          { name: "Western Highlands Province", code: "WHP", region: "Highlands" },
          { name: "Morobe Province", code: "MBP", region: "Momase" },
          { name: "East Sepik Province", code: "ESP", region: "Momase" },
          { name: "National Capital District", code: "NCD", region: "Papua" },
          { name: "Southern Highlands Province", code: "SHP", region: "Highlands" },
          { name: "Enga Province", code: "EPG", region: "Highlands" },
          { name: "Madang Province", code: "MPL", region: "Momase" },
          { name: "New Ireland Province", code: "NIP", region: "Islands" },
        ])
        .returning();

      console.log(`Inserted ${insertedProvinces.length} provinces`);

      const provinceMap: Record<string, number> = {};
      for (const p of insertedProvinces) {
        provinceMap[p.code] = p.id;
      }

      const insertedDistricts = await tx
        .insert(districts)
        .values([
          { name: "Rigo District", code: "CPL-RIG", provinceId: provinceMap["CPL"] },
          { name: "Abau District", code: "CPL-ABU", provinceId: provinceMap["CPL"] },
          { name: "Goilala District", code: "CPL-GOI", provinceId: provinceMap["CPL"] },
          { name: "Kainantu District", code: "EHP-KAI", provinceId: provinceMap["EHP"] },
          { name: "Goroka District", code: "EHP-GOR", provinceId: provinceMap["EHP"] },
          { name: "Okapa District", code: "EHP-OKA", provinceId: provinceMap["EHP"] },
          { name: "Mount Hagen District", code: "WHP-MHG", provinceId: provinceMap["WHP"] },
          { name: "Tambul-Nebilyer District", code: "WHP-TNB", provinceId: provinceMap["WHP"] },
          { name: "Dei District", code: "WHP-DEI", provinceId: provinceMap["WHP"] },
          { name: "Lae District", code: "MBP-LAE", provinceId: provinceMap["MBP"] },
          { name: "Huon District", code: "MBP-HUN", provinceId: provinceMap["MBP"] },
          { name: "Finschhafen District", code: "MBP-FIN", provinceId: provinceMap["MBP"] },
          { name: "Wewak District", code: "ESP-WEW", provinceId: provinceMap["ESP"] },
          { name: "Angoram District", code: "ESP-ANG", provinceId: provinceMap["ESP"] },
          { name: "Motu-Koita District", code: "NCD-MOT", provinceId: provinceMap["NCD"] },
          { name: "Mendi District", code: "SHP-MEN", provinceId: provinceMap["SHP"] },
          { name: "Nipa-Kutubu District", code: "SHP-NIK", provinceId: provinceMap["SHP"] },
          { name: "Wabag District", code: "EPG-WAB", provinceId: provinceMap["EPG"] },
          { name: "Madang District", code: "MPL-MAD", provinceId: provinceMap["MPL"] },
          { name: "Kavieng District", code: "NIP-KAV", provinceId: provinceMap["NIP"] },
        ])
        .returning();

      console.log(`Inserted ${insertedDistricts.length} districts`);

      const districtMap: Record<string, number> = {};
      for (const d of insertedDistricts) {
        districtMap[d.code] = d.id;
      }

      const insertedFacilities = await tx
        .insert(facilities)
        .values([
          {
            name: "Rigo Health Centre",
            hmisCode: "CPL-RIG-HC01",
            facilityType: "Health Centre",
            districtId: districtMap["CPL-RIG"],
            latitude: "-9.8833",
            longitude: "147.6500",
            hasRefrigerator: true,
            hasPower: true,
            staffCount: 8,
            isActive: true,
          },
          {
            name: "Kwikila Health Post",
            hmisCode: "CPL-RIG-HP01",
            facilityType: "Health Post",
            districtId: districtMap["CPL-RIG"],
            latitude: "-9.9167",
            longitude: "147.7167",
            hasRefrigerator: false,
            hasPower: false,
            staffCount: 3,
            isActive: true,
          },
          {
            name: "Abau Health Centre",
            hmisCode: "CPL-ABU-HC01",
            facilityType: "Health Centre",
            districtId: districtMap["CPL-ABU"],
            latitude: "-10.0833",
            longitude: "148.3833",
            hasRefrigerator: true,
            hasPower: true,
            staffCount: 6,
            isActive: true,
          },
          {
            name: "Goilala Health Centre",
            hmisCode: "CPL-GOI-HC01",
            facilityType: "Health Centre",
            districtId: districtMap["CPL-GOI"],
            latitude: "-8.3333",
            longitude: "146.8333",
            hasRefrigerator: true,
            hasPower: false,
            staffCount: 5,
            isActive: true,
          },
          {
            name: "Kainantu Rural Hospital",
            hmisCode: "EHP-KAI-RH01",
            facilityType: "Rural Hospital",
            districtId: districtMap["EHP-KAI"],
            latitude: "-6.2833",
            longitude: "145.8667",
            hasRefrigerator: true,
            hasPower: true,
            staffCount: 25,
            isActive: true,
          },
          {
            name: "Aiyura Health Centre",
            hmisCode: "EHP-KAI-HC01",
            facilityType: "Health Centre",
            districtId: districtMap["EHP-KAI"],
            latitude: "-6.3333",
            longitude: "145.9000",
            hasRefrigerator: true,
            hasPower: true,
            staffCount: 10,
            isActive: true,
          },
          {
            name: "Goroka Base Hospital",
            hmisCode: "EHP-GOR-BH01",
            facilityType: "Base Hospital",
            districtId: districtMap["EHP-GOR"],
            latitude: "-6.0833",
            longitude: "145.3833",
            hasRefrigerator: true,
            hasPower: true,
            staffCount: 120,
            isActive: true,
          },
          {
            name: "Okapa Health Centre",
            hmisCode: "EHP-OKA-HC01",
            facilityType: "Health Centre",
            districtId: districtMap["EHP-OKA"],
            latitude: "-6.5500",
            longitude: "145.6167",
            hasRefrigerator: true,
            hasPower: false,
            staffCount: 7,
            isActive: true,
          },
          {
            name: "Mount Hagen Provincial Hospital",
            hmisCode: "WHP-MHG-PH01",
            facilityType: "Provincial Hospital",
            districtId: districtMap["WHP-MHG"],
            latitude: "-5.8500",
            longitude: "144.2333",
            hasRefrigerator: true,
            hasPower: true,
            staffCount: 150,
            isActive: true,
          },
          {
            name: "Kotna Health Centre",
            hmisCode: "WHP-MHG-HC01",
            facilityType: "Health Centre",
            districtId: districtMap["WHP-MHG"],
            latitude: "-5.8667",
            longitude: "144.2000",
            hasRefrigerator: true,
            hasPower: true,
            staffCount: 12,
            isActive: true,
          },
          {
            name: "Tambul Health Centre",
            hmisCode: "WHP-TNB-HC01",
            facilityType: "Health Centre",
            districtId: districtMap["WHP-TNB"],
            latitude: "-5.9167",
            longitude: "143.8667",
            hasRefrigerator: true,
            hasPower: false,
            staffCount: 7,
            isActive: true,
          },
          {
            name: "Anglimp Aid Post",
            hmisCode: "WHP-TNB-AP01",
            facilityType: "Aid Post",
            districtId: districtMap["WHP-TNB"],
            latitude: "-5.9500",
            longitude: "143.8333",
            hasRefrigerator: false,
            hasPower: false,
            staffCount: 2,
            isActive: true,
          },
          {
            name: "Dei Health Centre",
            hmisCode: "WHP-DEI-HC01",
            facilityType: "Health Centre",
            districtId: districtMap["WHP-DEI"],
            latitude: "-5.7500",
            longitude: "144.0833",
            hasRefrigerator: true,
            hasPower: true,
            staffCount: 8,
            isActive: true,
          },
          {
            name: "Angau Memorial Hospital",
            hmisCode: "MBP-LAE-PH01",
            facilityType: "Provincial Hospital",
            districtId: districtMap["MBP-LAE"],
            latitude: "-6.7333",
            longitude: "147.0000",
            hasRefrigerator: true,
            hasPower: true,
            staffCount: 200,
            isActive: true,
          },
          {
            name: "Eriku Urban Clinic",
            hmisCode: "MBP-LAE-UC01",
            facilityType: "Urban Clinic",
            districtId: districtMap["MBP-LAE"],
            latitude: "-6.7167",
            longitude: "146.9833",
            hasRefrigerator: true,
            hasPower: true,
            staffCount: 15,
            isActive: true,
          },
          {
            name: "Finschhafen Health Centre",
            hmisCode: "MBP-FIN-HC01",
            facilityType: "Health Centre",
            districtId: districtMap["MBP-FIN"],
            latitude: "-6.5833",
            longitude: "147.8500",
            hasRefrigerator: true,
            hasPower: true,
            staffCount: 10,
            isActive: true,
          },
          {
            name: "Huon District Hospital",
            hmisCode: "MBP-HUN-DH01",
            facilityType: "District Hospital",
            districtId: districtMap["MBP-HUN"],
            latitude: "-6.4833",
            longitude: "147.7833",
            hasRefrigerator: true,
            hasPower: true,
            staffCount: 35,
            isActive: true,
          },
          {
            name: "Wewak General Hospital",
            hmisCode: "ESP-WEW-GH01",
            facilityType: "General Hospital",
            districtId: districtMap["ESP-WEW"],
            latitude: "-3.5500",
            longitude: "143.6333",
            hasRefrigerator: true,
            hasPower: true,
            staffCount: 80,
            isActive: true,
          },
          {
            name: "Angoram Health Centre",
            hmisCode: "ESP-ANG-HC01",
            facilityType: "Health Centre",
            districtId: districtMap["ESP-ANG"],
            latitude: "-4.0500",
            longitude: "144.0667",
            hasRefrigerator: true,
            hasPower: false,
            staffCount: 9,
            isActive: true,
          },
          {
            name: "Port Moresby General Hospital",
            hmisCode: "NCD-MOT-GH01",
            facilityType: "General Hospital",
            districtId: districtMap["NCD-MOT"],
            latitude: "-9.4500",
            longitude: "147.1833",
            hasRefrigerator: true,
            hasPower: true,
            staffCount: 300,
            isActive: true,
          },
          {
            name: "Mendi Hospital",
            hmisCode: "SHP-MEN-PH01",
            facilityType: "Provincial Hospital",
            districtId: districtMap["SHP-MEN"],
            latitude: "-6.1500",
            longitude: "143.6500",
            hasRefrigerator: true,
            hasPower: true,
            staffCount: 85,
            isActive: true,
          },
          {
            name: "Nipa Health Centre",
            hmisCode: "SHP-NIK-HC01",
            facilityType: "Health Centre",
            districtId: districtMap["SHP-NIK"],
            latitude: "-6.1167",
            longitude: "143.4667",
            hasRefrigerator: true,
            hasPower: false,
            staffCount: 8,
            isActive: true,
          },
          {
            name: "Wabag Hospital",
            hmisCode: "EPG-WAB-PH01",
            facilityType: "Provincial Hospital",
            districtId: districtMap["EPG-WAB"],
            latitude: "-5.4833",
            longitude: "143.7167",
            hasRefrigerator: true,
            hasPower: true,
            staffCount: 70,
            isActive: true,
          },
          {
            name: "Madang Provincial Hospital",
            hmisCode: "MPL-MAD-PH01",
            facilityType: "Provincial Hospital",
            districtId: districtMap["MPL-MAD"],
            latitude: "-5.2167",
            longitude: "145.8000",
            hasRefrigerator: true,
            hasPower: true,
            staffCount: 95,
            isActive: true,
          },
          {
            name: "Kavieng Hospital",
            hmisCode: "NIP-KAV-PH01",
            facilityType: "Provincial Hospital",
            districtId: districtMap["NIP-KAV"],
            latitude: "-2.5667",
            longitude: "150.8000",
            hasRefrigerator: true,
            hasPower: true,
            staffCount: 60,
            isActive: true,
          },
        ])
        .returning();

      console.log(`Inserted ${insertedFacilities.length} facilities`);

      const facilityMap: Record<string, number> = {};
      for (const f of insertedFacilities) {
        facilityMap[f.hmisCode] = f.id;
      }

      const insertedVillages = await tx
        .insert(villages)
        .values([
          {
            name: "Rigo Village",
            code: "CPL-RIG-V001",
            districtId: districtMap["CPL-RIG"],
            assignedFacilityId: facilityMap["CPL-RIG-HC01"],
            latitude: "-9.8900",
            longitude: "147.6550",
            distanceToFacility: "2.5",
            travelTimeMinutes: 30,
            terrainDifficulty: 2,
            isHardToReach: false,
            transportMode: "road",
          },
          {
            name: "Hula Village",
            code: "CPL-RIG-V002",
            districtId: districtMap["CPL-RIG"],
            assignedFacilityId: facilityMap["CPL-RIG-HC01"],
            latitude: "-10.0500",
            longitude: "147.6833",
            distanceToFacility: "15.0",
            travelTimeMinutes: 90,
            terrainDifficulty: 4,
            isHardToReach: true,
            transportMode: "boat",
          },
          {
            name: "Kwikila Village",
            code: "CPL-RIG-V003",
            districtId: districtMap["CPL-RIG"],
            assignedFacilityId: facilityMap["CPL-RIG-HP01"],
            latitude: "-9.9200",
            longitude: "147.7200",
            distanceToFacility: "1.2",
            travelTimeMinutes: 15,
            terrainDifficulty: 1,
            isHardToReach: false,
            transportMode: "walking",
          },
          {
            name: "Abau Village",
            code: "CPL-ABU-V001",
            districtId: districtMap["CPL-ABU"],
            assignedFacilityId: facilityMap["CPL-ABU-HC01"],
            latitude: "-10.0850",
            longitude: "148.3850",
            distanceToFacility: "0.5",
            travelTimeMinutes: 10,
            terrainDifficulty: 1,
            isHardToReach: false,
            transportMode: "walking",
          },
          {
            name: "Amazon Bay",
            code: "CPL-ABU-V002",
            districtId: districtMap["CPL-ABU"],
            assignedFacilityId: facilityMap["CPL-ABU-HC01"],
            latitude: "-10.2000",
            longitude: "148.5000",
            distanceToFacility: "25.0",
            travelTimeMinutes: 180,
            terrainDifficulty: 5,
            isHardToReach: true,
            transportMode: "boat",
          },
          {
            name: "Tapini Station",
            code: "CPL-GOI-V001",
            districtId: districtMap["CPL-GOI"],
            assignedFacilityId: facilityMap["CPL-GOI-HC01"],
            latitude: "-8.3500",
            longitude: "146.8500",
            distanceToFacility: "3.0",
            travelTimeMinutes: 45,
            terrainDifficulty: 3,
            isHardToReach: false,
            transportMode: "walking",
          },
          {
            name: "Woitape Village",
            code: "CPL-GOI-V002",
            districtId: districtMap["CPL-GOI"],
            assignedFacilityId: facilityMap["CPL-GOI-HC01"],
            latitude: "-8.5000",
            longitude: "147.0000",
            distanceToFacility: "20.0",
            travelTimeMinutes: 300,
            terrainDifficulty: 5,
            isHardToReach: true,
            transportMode: "walking",
          },
          {
            name: "Kainantu Town",
            code: "EHP-KAI-V001",
            districtId: districtMap["EHP-KAI"],
            assignedFacilityId: facilityMap["EHP-KAI-RH01"],
            latitude: "-6.2850",
            longitude: "145.8700",
            distanceToFacility: "0.3",
            travelTimeMinutes: 5,
            terrainDifficulty: 1,
            isHardToReach: false,
            transportMode: "walking",
          },
          {
            name: "Aiyura Valley",
            code: "EHP-KAI-V002",
            districtId: districtMap["EHP-KAI"],
            assignedFacilityId: facilityMap["EHP-KAI-HC01"],
            latitude: "-6.3400",
            longitude: "145.9050",
            distanceToFacility: "1.0",
            travelTimeMinutes: 15,
            terrainDifficulty: 2,
            isHardToReach: false,
            transportMode: "road",
          },
          {
            name: "Kami Settlement",
            code: "EHP-KAI-V003",
            districtId: districtMap["EHP-KAI"],
            assignedFacilityId: facilityMap["EHP-KAI-HC01"],
            latitude: "-6.4000",
            longitude: "145.9500",
            distanceToFacility: "12.0",
            travelTimeMinutes: 120,
            terrainDifficulty: 4,
            isHardToReach: true,
            transportMode: "walking",
          },
          {
            name: "Goroka Town",
            code: "EHP-GOR-V001",
            districtId: districtMap["EHP-GOR"],
            assignedFacilityId: facilityMap["EHP-GOR-BH01"],
            latitude: "-6.0850",
            longitude: "145.3850",
            distanceToFacility: "0.2",
            travelTimeMinutes: 3,
            terrainDifficulty: 1,
            isHardToReach: false,
            transportMode: "walking",
          },
          {
            name: "Asaro Village",
            code: "EHP-GOR-V002",
            districtId: districtMap["EHP-GOR"],
            assignedFacilityId: facilityMap["EHP-GOR-BH01"],
            latitude: "-6.0000",
            longitude: "145.5000",
            distanceToFacility: "15.0",
            travelTimeMinutes: 60,
            terrainDifficulty: 2,
            isHardToReach: false,
            transportMode: "road",
          },
          {
            name: "Okapa Station",
            code: "EHP-OKA-V001",
            districtId: districtMap["EHP-OKA"],
            assignedFacilityId: facilityMap["EHP-OKA-HC01"],
            latitude: "-6.5550",
            longitude: "145.6200",
            distanceToFacility: "0.8",
            travelTimeMinutes: 12,
            terrainDifficulty: 2,
            isHardToReach: false,
            transportMode: "walking",
          },
          {
            name: "Mount Hagen Town",
            code: "WHP-MHG-V001",
            districtId: districtMap["WHP-MHG"],
            assignedFacilityId: facilityMap["WHP-MHG-PH01"],
            latitude: "-5.8520",
            longitude: "144.2350",
            distanceToFacility: "0.4",
            travelTimeMinutes: 5,
            terrainDifficulty: 1,
            isHardToReach: false,
            transportMode: "walking",
          },
          {
            name: "Kotna Village",
            code: "WHP-MHG-V002",
            districtId: districtMap["WHP-MHG"],
            assignedFacilityId: facilityMap["WHP-MHG-HC01"],
            latitude: "-5.8700",
            longitude: "144.2050",
            distanceToFacility: "0.8",
            travelTimeMinutes: 10,
            terrainDifficulty: 2,
            isHardToReach: false,
            transportMode: "walking",
          },
          {
            name: "Baiyer River",
            code: "WHP-MHG-V003",
            districtId: districtMap["WHP-MHG"],
            assignedFacilityId: facilityMap["WHP-MHG-HC01"],
            latitude: "-5.5500",
            longitude: "144.1667",
            distanceToFacility: "35.0",
            travelTimeMinutes: 240,
            terrainDifficulty: 5,
            isHardToReach: true,
            transportMode: "road",
          },
          {
            name: "Tambul Village",
            code: "WHP-TNB-V001",
            districtId: districtMap["WHP-TNB"],
            assignedFacilityId: facilityMap["WHP-TNB-HC01"],
            latitude: "-5.9200",
            longitude: "143.8700",
            distanceToFacility: "0.5",
            travelTimeMinutes: 8,
            terrainDifficulty: 1,
            isHardToReach: false,
            transportMode: "walking",
          },
          {
            name: "Anglimp Village",
            code: "WHP-TNB-V002",
            districtId: districtMap["WHP-TNB"],
            assignedFacilityId: facilityMap["WHP-TNB-AP01"],
            latitude: "-5.9550",
            longitude: "143.8350",
            distanceToFacility: "0.6",
            travelTimeMinutes: 10,
            terrainDifficulty: 2,
            isHardToReach: false,
            transportMode: "walking",
          },
          {
            name: "Nebilyer Valley",
            code: "WHP-TNB-V003",
            districtId: districtMap["WHP-TNB"],
            assignedFacilityId: facilityMap["WHP-TNB-HC01"],
            latitude: "-5.8000",
            longitude: "143.7500",
            distanceToFacility: "18.0",
            travelTimeMinutes: 150,
            terrainDifficulty: 4,
            isHardToReach: true,
            transportMode: "road",
          },
          {
            name: "Dei Station",
            code: "WHP-DEI-V001",
            districtId: districtMap["WHP-DEI"],
            assignedFacilityId: facilityMap["WHP-DEI-HC01"],
            latitude: "-5.7550",
            longitude: "144.0850",
            distanceToFacility: "0.6",
            travelTimeMinutes: 8,
            terrainDifficulty: 1,
            isHardToReach: false,
            transportMode: "walking",
          },
          {
            name: "Lae City",
            code: "MBP-LAE-V001",
            districtId: districtMap["MBP-LAE"],
            assignedFacilityId: facilityMap["MBP-LAE-PH01"],
            latitude: "-6.7350",
            longitude: "147.0050",
            distanceToFacility: "0.3",
            travelTimeMinutes: 5,
            terrainDifficulty: 1,
            isHardToReach: false,
            transportMode: "walking",
          },
          {
            name: "Eriku Settlement",
            code: "MBP-LAE-V002",
            districtId: districtMap["MBP-LAE"],
            assignedFacilityId: facilityMap["MBP-LAE-UC01"],
            latitude: "-6.7200",
            longitude: "146.9850",
            distanceToFacility: "0.5",
            travelTimeMinutes: 8,
            terrainDifficulty: 1,
            isHardToReach: false,
            transportMode: "walking",
          },
          {
            name: "Finschhafen Town",
            code: "MBP-FIN-V001",
            districtId: districtMap["MBP-FIN"],
            assignedFacilityId: facilityMap["MBP-FIN-HC01"],
            latitude: "-6.5850",
            longitude: "147.8520",
            distanceToFacility: "0.4",
            travelTimeMinutes: 6,
            terrainDifficulty: 1,
            isHardToReach: false,
            transportMode: "walking",
          },
          {
            name: "Sialum Village",
            code: "MBP-HUN-V001",
            districtId: districtMap["MBP-HUN"],
            assignedFacilityId: facilityMap["MBP-HUN-DH01"],
            latitude: "-6.1000",
            longitude: "147.6000",
            distanceToFacility: "45.0",
            travelTimeMinutes: 360,
            terrainDifficulty: 5,
            isHardToReach: true,
            transportMode: "boat",
          },
          {
            name: "Huon Bay",
            code: "MBP-HUN-V002",
            districtId: districtMap["MBP-HUN"],
            assignedFacilityId: facilityMap["MBP-HUN-DH01"],
            latitude: "-6.4900",
            longitude: "147.7900",
            distanceToFacility: "1.2",
            travelTimeMinutes: 15,
            terrainDifficulty: 1,
            isHardToReach: false,
            transportMode: "walking",
          },
          {
            name: "Wewak Town",
            code: "ESP-WEW-V001",
            districtId: districtMap["ESP-WEW"],
            assignedFacilityId: facilityMap["ESP-WEW-GH01"],
            latitude: "-3.5520",
            longitude: "143.6350",
            distanceToFacility: "0.3",
            travelTimeMinutes: 5,
            terrainDifficulty: 1,
            isHardToReach: false,
            transportMode: "walking",
          },
          {
            name: "But Village",
            code: "ESP-WEW-V002",
            districtId: districtMap["ESP-WEW"],
            assignedFacilityId: facilityMap["ESP-WEW-GH01"],
            latitude: "-3.4833",
            longitude: "143.5667",
            distanceToFacility: "10.0",
            travelTimeMinutes: 45,
            terrainDifficulty: 2,
            isHardToReach: false,
            transportMode: "road",
          },
          {
            name: "Angoram Station",
            code: "ESP-ANG-V001",
            districtId: districtMap["ESP-ANG"],
            assignedFacilityId: facilityMap["ESP-ANG-HC01"],
            latitude: "-4.0550",
            longitude: "144.0700",
            distanceToFacility: "0.5",
            travelTimeMinutes: 8,
            terrainDifficulty: 1,
            isHardToReach: false,
            transportMode: "walking",
          },
          {
            name: "Sepik River Village",
            code: "ESP-ANG-V002",
            districtId: districtMap["ESP-ANG"],
            assignedFacilityId: facilityMap["ESP-ANG-HC01"],
            latitude: "-4.2000",
            longitude: "144.2500",
            distanceToFacility: "30.0",
            travelTimeMinutes: 180,
            terrainDifficulty: 4,
            isHardToReach: true,
            transportMode: "boat",
          },
          {
            name: "Port Moresby - Motu-Koita",
            code: "NCD-MOT-V001",
            districtId: districtMap["NCD-MOT"],
            assignedFacilityId: facilityMap["NCD-MOT-GH01"],
            latitude: "-9.4520",
            longitude: "147.1850",
            distanceToFacility: "0.2",
            travelTimeMinutes: 3,
            terrainDifficulty: 1,
            isHardToReach: false,
            transportMode: "walking",
          },
          {
            name: "Mendi Town",
            code: "SHP-MEN-V001",
            districtId: districtMap["SHP-MEN"],
            assignedFacilityId: facilityMap["SHP-MEN-PH01"],
            latitude: "-6.1550",
            longitude: "143.6550",
            distanceToFacility: "0.5",
            travelTimeMinutes: 8,
            terrainDifficulty: 1,
            isHardToReach: false,
            transportMode: "walking",
          },
          {
            name: "Nipa Station",
            code: "SHP-NIK-V001",
            districtId: districtMap["SHP-NIK"],
            assignedFacilityId: facilityMap["SHP-NIK-HC01"],
            latitude: "-6.1200",
            longitude: "143.4700",
            distanceToFacility: "0.4",
            travelTimeMinutes: 6,
            terrainDifficulty: 1,
            isHardToReach: false,
            transportMode: "walking",
          },
          {
            name: "Lake Kutubu",
            code: "SHP-NIK-V002",
            districtId: districtMap["SHP-NIK"],
            assignedFacilityId: facilityMap["SHP-NIK-HC01"],
            latitude: "-6.4000",
            longitude: "143.3000",
            distanceToFacility: "40.0",
            travelTimeMinutes: 300,
            terrainDifficulty: 5,
            isHardToReach: true,
            transportMode: "boat",
          },
          {
            name: "Wabag Town",
            code: "EPG-WAB-V001",
            districtId: districtMap["EPG-WAB"],
            assignedFacilityId: facilityMap["EPG-WAB-PH01"],
            latitude: "-5.4850",
            longitude: "143.7200",
            distanceToFacility: "0.3",
            travelTimeMinutes: 5,
            terrainDifficulty: 1,
            isHardToReach: false,
            transportMode: "walking",
          },
          {
            name: "Madang Town",
            code: "MPL-MAD-V001",
            districtId: districtMap["MPL-MAD"],
            assignedFacilityId: facilityMap["MPL-MAD-PH01"],
            latitude: "-5.2200",
            longitude: "145.8050",
            distanceToFacility: "0.4",
            travelTimeMinutes: 5,
            terrainDifficulty: 1,
            isHardToReach: false,
            transportMode: "walking",
          },
          {
            name: "Siar Village",
            code: "MPL-MAD-V002",
            districtId: districtMap["MPL-MAD"],
            assignedFacilityId: facilityMap["MPL-MAD-PH01"],
            latitude: "-5.1500",
            longitude: "145.7500",
            distanceToFacility: "12.0",
            travelTimeMinutes: 45,
            terrainDifficulty: 2,
            isHardToReach: false,
            transportMode: "road",
          },
          {
            name: "Kavieng Town",
            code: "NIP-KAV-V001",
            districtId: districtMap["NIP-KAV"],
            assignedFacilityId: facilityMap["NIP-KAV-PH01"],
            latitude: "-2.5700",
            longitude: "150.8050",
            distanceToFacility: "0.3",
            travelTimeMinutes: 5,
            terrainDifficulty: 1,
            isHardToReach: false,
            transportMode: "walking",
          },
          {
            name: "Tigak Islands",
            code: "NIP-KAV-V002",
            districtId: districtMap["NIP-KAV"],
            assignedFacilityId: facilityMap["NIP-KAV-PH01"],
            latitude: "-2.4000",
            longitude: "150.9500",
            distanceToFacility: "25.0",
            travelTimeMinutes: 120,
            terrainDifficulty: 4,
            isHardToReach: true,
            transportMode: "boat",
          },
        ])
        .returning();

      console.log(`Inserted ${insertedVillages.length} villages`);

      const villageMap: Record<string, number> = {};
      for (const v of insertedVillages) {
        if (v.code) {
          villageMap[v.code] = v.id;
        }
      }

      const currentYear = new Date().getFullYear();

      function calcPopData(total: number, source: "census" | "local_survey" | "remote_sensing" | "worldpop" | "health_registry") {
        const male = Math.round(total * 0.51);
        const female = total - male;
        const under1 = Math.round(total * 0.038);
        const under5 = Math.round(total * 0.16);
        const pregnant = Math.round(female * 0.045);
        const confidence = source === "census" ? "95.00" : 
                          source === "local_survey" ? "85.00" :
                          source === "health_registry" ? "88.00" :
                          source === "worldpop" ? "75.00" : "65.00";
        const status = source === "remote_sensing" || source === "worldpop" ? "pending" : "approved";
        return { male, female, under1, under5, pregnant, confidence, status };
      }
      
      const rawPopulationValues = [
          {
            villageId: villageMap["CPL-RIG-V001"],
            source: "census",
            year: currentYear,
            totalPopulation: 1250,
            malePopulation: calcPopData(1250, "census").male,
            femalePopulation: calcPopData(1250, "census").female,
            under1Population: calcPopData(1250, "census").under1,
            under5Population: calcPopData(1250, "census").under5,
            pregnantWomen: calcPopData(1250, "census").pregnant,
            confidenceScore: calcPopData(1250, "census").confidence,
            approvalStatus: "approved",
          },
          {
            villageId: villageMap["CPL-RIG-V002"],
            source: "local_survey",
            year: currentYear,
            totalPopulation: 420,
            malePopulation: calcPopData(420, "local_survey").male,
            femalePopulation: calcPopData(420, "local_survey").female,
            under1Population: calcPopData(420, "local_survey").under1,
            under5Population: calcPopData(420, "local_survey").under5,
            pregnantWomen: calcPopData(420, "local_survey").pregnant,
            confidenceScore: calcPopData(420, "local_survey").confidence,
            approvalStatus: "approved",
          },
          {
            villageId: villageMap["CPL-RIG-V003"],
            source: "census",
            year: currentYear,
            totalPopulation: 680,
            malePopulation: calcPopData(680, "census").male,
            femalePopulation: calcPopData(680, "census").female,
            under1Population: calcPopData(680, "census").under1,
            under5Population: calcPopData(680, "census").under5,
            pregnantWomen: calcPopData(680, "census").pregnant,
            confidenceScore: calcPopData(680, "census").confidence,
            approvalStatus: "approved",
          },
          {
            villageId: villageMap["CPL-ABU-V001"],
            source: "census",
            year: currentYear,
            totalPopulation: 890,
            malePopulation: calcPopData(890, "census").male,
            femalePopulation: calcPopData(890, "census").female,
            under1Population: calcPopData(890, "census").under1,
            under5Population: calcPopData(890, "census").under5,
            pregnantWomen: calcPopData(890, "census").pregnant,
            confidenceScore: calcPopData(890, "census").confidence,
            approvalStatus: "approved",
          },
          {
            villageId: villageMap["CPL-ABU-V002"],
            source: "remote_sensing",
            year: currentYear,
            totalPopulation: 280,
            malePopulation: calcPopData(280, "remote_sensing").male,
            femalePopulation: calcPopData(280, "remote_sensing").female,
            under1Population: calcPopData(280, "remote_sensing").under1,
            under5Population: calcPopData(280, "remote_sensing").under5,
            pregnantWomen: calcPopData(280, "remote_sensing").pregnant,
            confidenceScore: calcPopData(280, "remote_sensing").confidence,
            approvalStatus: "pending",
          },
          {
            villageId: villageMap["CPL-GOI-V001"],
            source: "census",
            year: currentYear,
            totalPopulation: 1100,
            malePopulation: calcPopData(1100, "census").male,
            femalePopulation: calcPopData(1100, "census").female,
            under1Population: calcPopData(1100, "census").under1,
            under5Population: calcPopData(1100, "census").under5,
            pregnantWomen: calcPopData(1100, "census").pregnant,
            confidenceScore: calcPopData(1100, "census").confidence,
            approvalStatus: "approved",
          },
          {
            villageId: villageMap["CPL-GOI-V002"],
            source: "local_survey",
            year: currentYear,
            totalPopulation: 340,
            malePopulation: calcPopData(340, "local_survey").male,
            femalePopulation: calcPopData(340, "local_survey").female,
            under1Population: calcPopData(340, "local_survey").under1,
            under5Population: calcPopData(340, "local_survey").under5,
            pregnantWomen: calcPopData(340, "local_survey").pregnant,
            confidenceScore: calcPopData(340, "local_survey").confidence,
            approvalStatus: "approved",
          },
          {
            villageId: villageMap["EHP-KAI-V001"],
            source: "census",
            year: currentYear,
            totalPopulation: 4200,
            malePopulation: calcPopData(4200, "census").male,
            femalePopulation: calcPopData(4200, "census").female,
            under1Population: calcPopData(4200, "census").under1,
            under5Population: calcPopData(4200, "census").under5,
            pregnantWomen: calcPopData(4200, "census").pregnant,
            confidenceScore: calcPopData(4200, "census").confidence,
            approvalStatus: "approved",
          },
          {
            villageId: villageMap["EHP-KAI-V002"],
            source: "census",
            year: currentYear,
            totalPopulation: 1580,
            malePopulation: calcPopData(1580, "census").male,
            femalePopulation: calcPopData(1580, "census").female,
            under1Population: calcPopData(1580, "census").under1,
            under5Population: calcPopData(1580, "census").under5,
            pregnantWomen: calcPopData(1580, "census").pregnant,
            confidenceScore: calcPopData(1580, "census").confidence,
            approvalStatus: "approved",
          },
          {
            villageId: villageMap["EHP-KAI-V003"],
            source: "local_survey",
            year: currentYear,
            totalPopulation: 380,
            malePopulation: calcPopData(380, "local_survey").male,
            femalePopulation: calcPopData(380, "local_survey").female,
            under1Population: calcPopData(380, "local_survey").under1,
            under5Population: calcPopData(380, "local_survey").under5,
            pregnantWomen: calcPopData(380, "local_survey").pregnant,
            confidenceScore: calcPopData(380, "local_survey").confidence,
            approvalStatus: "approved",
          },
          {
            villageId: villageMap["EHP-GOR-V001"],
            source: "census",
            year: currentYear,
            totalPopulation: 6500,
            malePopulation: calcPopData(6500, "census").male,
            femalePopulation: calcPopData(6500, "census").female,
            under1Population: calcPopData(6500, "census").under1,
            under5Population: calcPopData(6500, "census").under5,
            pregnantWomen: calcPopData(6500, "census").pregnant,
            confidenceScore: calcPopData(6500, "census").confidence,
            approvalStatus: "approved",
          },
          {
            villageId: villageMap["EHP-GOR-V002"],
            source: "census",
            year: currentYear,
            totalPopulation: 920,
            malePopulation: calcPopData(920, "census").male,
            femalePopulation: calcPopData(920, "census").female,
            under1Population: calcPopData(920, "census").under1,
            under5Population: calcPopData(920, "census").under5,
            pregnantWomen: calcPopData(920, "census").pregnant,
            confidenceScore: calcPopData(920, "census").confidence,
            approvalStatus: "approved",
          },
          {
            villageId: villageMap["EHP-OKA-V001"],
            source: "census",
            year: currentYear,
            totalPopulation: 1450,
            malePopulation: calcPopData(1450, "census").male,
            femalePopulation: calcPopData(1450, "census").female,
            under1Population: calcPopData(1450, "census").under1,
            under5Population: calcPopData(1450, "census").under5,
            pregnantWomen: calcPopData(1450, "census").pregnant,
            confidenceScore: calcPopData(1450, "census").confidence,
            approvalStatus: "approved",
          },
          {
            villageId: villageMap["WHP-MHG-V001"],
            source: "census",
            year: currentYear,
            totalPopulation: 8500,
            malePopulation: calcPopData(8500, "census").male,
            femalePopulation: calcPopData(8500, "census").female,
            under1Population: calcPopData(8500, "census").under1,
            under5Population: calcPopData(8500, "census").under5,
            pregnantWomen: calcPopData(8500, "census").pregnant,
            confidenceScore: calcPopData(8500, "census").confidence,
            approvalStatus: "approved",
          },
          {
            villageId: villageMap["WHP-MHG-V002"],
            source: "census",
            year: currentYear,
            totalPopulation: 780,
            malePopulation: calcPopData(780, "census").male,
            femalePopulation: calcPopData(780, "census").female,
            under1Population: calcPopData(780, "census").under1,
            under5Population: calcPopData(780, "census").under5,
            pregnantWomen: calcPopData(780, "census").pregnant,
            confidenceScore: calcPopData(780, "census").confidence,
            approvalStatus: "approved",
          },
          {
            villageId: villageMap["WHP-MHG-V003"],
            source: "worldpop",
            year: currentYear,
            totalPopulation: 1100,
            malePopulation: calcPopData(1100, "worldpop").male,
            femalePopulation: calcPopData(1100, "worldpop").female,
            under1Population: calcPopData(1100, "worldpop").under1,
            under5Population: calcPopData(1100, "worldpop").under5,
            pregnantWomen: calcPopData(1100, "worldpop").pregnant,
            confidenceScore: calcPopData(1100, "worldpop").confidence,
            approvalStatus: "pending",
          },
          {
            villageId: villageMap["WHP-TNB-V001"],
            source: "census",
            year: currentYear,
            totalPopulation: 1850,
            malePopulation: calcPopData(1850, "census").male,
            femalePopulation: calcPopData(1850, "census").female,
            under1Population: calcPopData(1850, "census").under1,
            under5Population: calcPopData(1850, "census").under5,
            pregnantWomen: calcPopData(1850, "census").pregnant,
            confidenceScore: calcPopData(1850, "census").confidence,
            approvalStatus: "approved",
          },
          {
            villageId: villageMap["WHP-TNB-V002"],
            source: "census",
            year: currentYear,
            totalPopulation: 920,
            malePopulation: calcPopData(920, "census").male,
            femalePopulation: calcPopData(920, "census").female,
            under1Population: calcPopData(920, "census").under1,
            under5Population: calcPopData(920, "census").under5,
            pregnantWomen: calcPopData(920, "census").pregnant,
            confidenceScore: calcPopData(920, "census").confidence,
            approvalStatus: "approved",
          },
          {
            villageId: villageMap["WHP-TNB-V003"],
            source: "local_survey",
            year: currentYear,
            totalPopulation: 480,
            malePopulation: calcPopData(480, "local_survey").male,
            femalePopulation: calcPopData(480, "local_survey").female,
            under1Population: calcPopData(480, "local_survey").under1,
            under5Population: calcPopData(480, "local_survey").under5,
            pregnantWomen: calcPopData(480, "local_survey").pregnant,
            confidenceScore: calcPopData(480, "local_survey").confidence,
            approvalStatus: "approved",
          },
          {
            villageId: villageMap["WHP-DEI-V001"],
            source: "census",
            year: currentYear,
            totalPopulation: 1320,
            malePopulation: calcPopData(1320, "census").male,
            femalePopulation: calcPopData(1320, "census").female,
            under1Population: calcPopData(1320, "census").under1,
            under5Population: calcPopData(1320, "census").under5,
            pregnantWomen: calcPopData(1320, "census").pregnant,
            confidenceScore: calcPopData(1320, "census").confidence,
            approvalStatus: "approved",
          },
          {
            villageId: villageMap["MBP-LAE-V001"],
            source: "census",
            year: currentYear,
            totalPopulation: 12000,
            malePopulation: calcPopData(12000, "census").male,
            femalePopulation: calcPopData(12000, "census").female,
            under1Population: calcPopData(12000, "census").under1,
            under5Population: calcPopData(12000, "census").under5,
            pregnantWomen: calcPopData(12000, "census").pregnant,
            confidenceScore: calcPopData(12000, "census").confidence,
            approvalStatus: "approved",
          },
          {
            villageId: villageMap["MBP-LAE-V002"],
            source: "census",
            year: currentYear,
            totalPopulation: 3200,
            malePopulation: calcPopData(3200, "census").male,
            femalePopulation: calcPopData(3200, "census").female,
            under1Population: calcPopData(3200, "census").under1,
            under5Population: calcPopData(3200, "census").under5,
            pregnantWomen: calcPopData(3200, "census").pregnant,
            confidenceScore: calcPopData(3200, "census").confidence,
            approvalStatus: "approved",
          },
          {
            villageId: villageMap["MBP-FIN-V001"],
            source: "census",
            year: currentYear,
            totalPopulation: 2100,
            malePopulation: calcPopData(2100, "census").male,
            femalePopulation: calcPopData(2100, "census").female,
            under1Population: calcPopData(2100, "census").under1,
            under5Population: calcPopData(2100, "census").under5,
            pregnantWomen: calcPopData(2100, "census").pregnant,
            confidenceScore: calcPopData(2100, "census").confidence,
            approvalStatus: "approved",
          },
          {
            villageId: villageMap["MBP-HUN-V001"],
            source: "remote_sensing",
            year: currentYear,
            totalPopulation: 180,
            malePopulation: calcPopData(180, "remote_sensing").male,
            femalePopulation: calcPopData(180, "remote_sensing").female,
            under1Population: calcPopData(180, "remote_sensing").under1,
            under5Population: calcPopData(180, "remote_sensing").under5,
            pregnantWomen: calcPopData(180, "remote_sensing").pregnant,
            confidenceScore: calcPopData(180, "remote_sensing").confidence,
            approvalStatus: "pending",
          },
          {
            villageId: villageMap["MBP-HUN-V002"],
            source: "census",
            year: currentYear,
            totalPopulation: 1560,
            malePopulation: calcPopData(1560, "census").male,
            femalePopulation: calcPopData(1560, "census").female,
            under1Population: calcPopData(1560, "census").under1,
            under5Population: calcPopData(1560, "census").under5,
            pregnantWomen: calcPopData(1560, "census").pregnant,
            confidenceScore: calcPopData(1560, "census").confidence,
            approvalStatus: "approved",
          },
          {
            villageId: villageMap["ESP-WEW-V001"],
            source: "census",
            year: currentYear,
            totalPopulation: 5800,
            malePopulation: calcPopData(5800, "census").male,
            femalePopulation: calcPopData(5800, "census").female,
            under1Population: calcPopData(5800, "census").under1,
            under5Population: calcPopData(5800, "census").under5,
            pregnantWomen: calcPopData(5800, "census").pregnant,
            confidenceScore: calcPopData(5800, "census").confidence,
            approvalStatus: "approved",
          },
          {
            villageId: villageMap["ESP-WEW-V002"],
            source: "census",
            year: currentYear,
            totalPopulation: 720,
            malePopulation: calcPopData(720, "census").male,
            femalePopulation: calcPopData(720, "census").female,
            under1Population: calcPopData(720, "census").under1,
            under5Population: calcPopData(720, "census").under5,
            pregnantWomen: calcPopData(720, "census").pregnant,
            confidenceScore: calcPopData(720, "census").confidence,
            approvalStatus: "approved",
          },
          {
            villageId: villageMap["ESP-ANG-V001"],
            source: "census",
            year: currentYear,
            totalPopulation: 1340,
            malePopulation: calcPopData(1340, "census").male,
            femalePopulation: calcPopData(1340, "census").female,
            under1Population: calcPopData(1340, "census").under1,
            under5Population: calcPopData(1340, "census").under5,
            pregnantWomen: calcPopData(1340, "census").pregnant,
            confidenceScore: calcPopData(1340, "census").confidence,
            approvalStatus: "approved",
          },
          {
            villageId: villageMap["ESP-ANG-V002"],
            source: "local_survey",
            year: currentYear,
            totalPopulation: 260,
            malePopulation: calcPopData(260, "local_survey").male,
            femalePopulation: calcPopData(260, "local_survey").female,
            under1Population: calcPopData(260, "local_survey").under1,
            under5Population: calcPopData(260, "local_survey").under5,
            pregnantWomen: calcPopData(260, "local_survey").pregnant,
            confidenceScore: calcPopData(260, "local_survey").confidence,
            approvalStatus: "approved",
          },
          {
            villageId: villageMap["NCD-MOT-V001"],
            source: "census",
            year: currentYear,
            totalPopulation: 15000,
            malePopulation: calcPopData(15000, "census").male,
            femalePopulation: calcPopData(15000, "census").female,
            under1Population: calcPopData(15000, "census").under1,
            under5Population: calcPopData(15000, "census").under5,
            pregnantWomen: calcPopData(15000, "census").pregnant,
            confidenceScore: calcPopData(15000, "census").confidence,
            approvalStatus: "approved",
          },
          {
            villageId: villageMap["SHP-MEN-V001"],
            source: "census",
            year: currentYear,
            totalPopulation: 4800,
            malePopulation: calcPopData(4800, "census").male,
            femalePopulation: calcPopData(4800, "census").female,
            under1Population: calcPopData(4800, "census").under1,
            under5Population: calcPopData(4800, "census").under5,
            pregnantWomen: calcPopData(4800, "census").pregnant,
            confidenceScore: calcPopData(4800, "census").confidence,
            approvalStatus: "approved",
          },
          {
            villageId: villageMap["SHP-NIK-V001"],
            source: "census",
            year: currentYear,
            totalPopulation: 1680,
            malePopulation: calcPopData(1680, "census").male,
            femalePopulation: calcPopData(1680, "census").female,
            under1Population: calcPopData(1680, "census").under1,
            under5Population: calcPopData(1680, "census").under5,
            pregnantWomen: calcPopData(1680, "census").pregnant,
            confidenceScore: calcPopData(1680, "census").confidence,
            approvalStatus: "approved",
          },
          {
            villageId: villageMap["SHP-NIK-V002"],
            source: "worldpop",
            year: currentYear,
            totalPopulation: 420,
            malePopulation: calcPopData(420, "worldpop").male,
            femalePopulation: calcPopData(420, "worldpop").female,
            under1Population: calcPopData(420, "worldpop").under1,
            under5Population: calcPopData(420, "worldpop").under5,
            pregnantWomen: calcPopData(420, "worldpop").pregnant,
            confidenceScore: calcPopData(420, "worldpop").confidence,
            approvalStatus: "pending",
          },
          {
            villageId: villageMap["EPG-WAB-V001"],
            source: "census",
            year: currentYear,
            totalPopulation: 5200,
            malePopulation: calcPopData(5200, "census").male,
            femalePopulation: calcPopData(5200, "census").female,
            under1Population: calcPopData(5200, "census").under1,
            under5Population: calcPopData(5200, "census").under5,
            pregnantWomen: calcPopData(5200, "census").pregnant,
            confidenceScore: calcPopData(5200, "census").confidence,
            approvalStatus: "approved",
          },
          {
            villageId: villageMap["MPL-MAD-V001"],
            source: "census",
            year: currentYear,
            totalPopulation: 7200,
            malePopulation: calcPopData(7200, "census").male,
            femalePopulation: calcPopData(7200, "census").female,
            under1Population: calcPopData(7200, "census").under1,
            under5Population: calcPopData(7200, "census").under5,
            pregnantWomen: calcPopData(7200, "census").pregnant,
            confidenceScore: calcPopData(7200, "census").confidence,
            approvalStatus: "approved",
          },
          {
            villageId: villageMap["MPL-MAD-V002"],
            source: "census",
            year: currentYear,
            totalPopulation: 580,
            malePopulation: calcPopData(580, "census").male,
            femalePopulation: calcPopData(580, "census").female,
            under1Population: calcPopData(580, "census").under1,
            under5Population: calcPopData(580, "census").under5,
            pregnantWomen: calcPopData(580, "census").pregnant,
            confidenceScore: calcPopData(580, "census").confidence,
            approvalStatus: "approved",
          },
          {
            villageId: villageMap["NIP-KAV-V001"],
            source: "census",
            year: currentYear,
            totalPopulation: 3100,
            malePopulation: calcPopData(3100, "census").male,
            femalePopulation: calcPopData(3100, "census").female,
            under1Population: calcPopData(3100, "census").under1,
            under5Population: calcPopData(3100, "census").under5,
            pregnantWomen: calcPopData(3100, "census").pregnant,
            confidenceScore: calcPopData(3100, "census").confidence,
            approvalStatus: "approved",
          },
          {
            villageId: villageMap["NIP-KAV-V002"],
            source: "local_survey",
            year: currentYear,
            totalPopulation: 350,
            malePopulation: calcPopData(350, "local_survey").male,
            femalePopulation: calcPopData(350, "local_survey").female,
            under1Population: calcPopData(350, "local_survey").under1,
            under5Population: calcPopData(350, "local_survey").under5,
            pregnantWomen: calcPopData(350, "local_survey").pregnant,
            confidenceScore: calcPopData(350, "local_survey").confidence,
            approvalStatus: "approved",
          },
        ];

      const populationSourceMap: Record<string, string> = {
        "census": "nso",
        "local_survey": "community_census",
        "remote_sensing": "worldpop",
        "health_registry": "hmis",
        "worldpop": "worldpop"
      };

      const mappedPopulationValues = rawPopulationValues.map(item => ({
        ...item,
        source: (populationSourceMap[item.source] || item.source) as "nso" | "hmis" | "worldpop" | "survey" | "community_census"
      }));

      const insertedPopulation = await tx
        .insert(populationData)
        .values(mappedPopulationValues)
        .returning();

      console.log(`Inserted ${insertedPopulation.length} population data records`);

      console.log("\nSeed completed successfully!");
      console.log(`Summary:
- ${insertedProvinces.length} provinces
- ${insertedDistricts.length} districts
- ${insertedFacilities.length} facilities
- ${insertedVillages.length} villages
- ${insertedPopulation.length} population records`);
    });

  } catch (error) {
    console.error("Error seeding database:", error);
    throw error;
  }
}

seedDatabase()
  .then(() => process.exit(0))
  .catch(() => process.exit(1));
