/**
 * realtime.ts — lightweight tenant-scoped websocket "change" channel.
 *
 * Goal: when one user/platform writes data, other connected clients viewing the
 * same tenant get a near-instant nudge to pull the latest changes — without
 * waiting for the periodic interval. It is layered on top of the reliable
 * pull/flush sync and degrades gracefully: if the socket can't connect (offline,
 * native cookie quirks, proxy issues) the interval sync still keeps everyone
 * eventually-consistent.
 *
 * Design notes:
 * - We never push row data over the socket. We only broadcast a small "changed"
 *   poke; the client responds with its normal authenticated `/api/sync/pull`,
 *   so all the existing tenant-scoping / auth rules are reused unchanged.
 * - Broadcasts are generated by a single Express `res.on('finish')` middleware
 *   that fires after ANY successful mutating `/api` request (covers both normal
 *   REST writes and the offline `/api/sync/batch` replay) — zero per-handler
 *   coupling.
 * - Pokes are debounced per tenant so a burst of writes collapses into one nudge.
 */

import type { Server, IncomingMessage } from "http";
import type { RequestHandler } from "express";
import { WebSocketServer, WebSocket } from "ws";
import { parse as parseUrl } from "url";

type TenantSockets = Set<WebSocket>;

const tenants = new Map<string, TenantSockets>();
const debounceTimers = new Map<string, NodeJS.Timeout>();
let wss: WebSocketServer | null = null;

const POKE_DEBOUNCE_MS = 400;
const KEEPALIVE_MS = 30_000;

const UUID_RE =
  /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

/**
 * Notify every client currently viewing `tenantId` that something changed.
 * Debounced per-tenant so a burst of writes produces a single nudge.
 */
export function broadcastTenantChange(
  tenantId: string | null | undefined,
  info: { entityTypes?: string[] } = {},
): void {
  if (!tenantId || !wss) return;
  const existing = debounceTimers.get(tenantId);
  if (existing) clearTimeout(existing);
  debounceTimers.set(
    tenantId,
    setTimeout(() => {
      debounceTimers.delete(tenantId);
      const set = tenants.get(tenantId);
      if (!set || set.size === 0) return;
      const msg = JSON.stringify({
        type: "changed",
        tenantId,
        at: new Date().toISOString(),
        ...info,
      });
      set.forEach((ws) => {
        if (ws.readyState === ws.OPEN) {
          try {
            ws.send(msg);
          } catch {
            /* ignore individual send failures */
          }
        }
      });
    }, POKE_DEBOUNCE_MS),
  );
}

/**
 * Express middleware: after any successful mutating /api request with a resolved
 * tenant, schedule a change poke for that tenant. GET/HEAD/OPTIONS never poke
 * (so a client's own pull can't create a feedback loop).
 */
export const realtimeBroadcastMiddleware: RequestHandler = (req, res, next) => {
  const method = req.method.toUpperCase();
  if (method === "GET" || method === "HEAD" || method === "OPTIONS") return next();
  if (!req.path.startsWith("/api/")) return next();
  res.on("finish", () => {
    if (res.statusCode >= 200 && res.statusCode < 300) {
      const tenantId = (req as any).tenantId as string | undefined;
      if (tenantId) broadcastTenantChange(tenantId);
    }
  });
  next();
};

/**
 * Attach the websocket server to the HTTP server. `sessionMiddleware` is the
 * same express-session instance used by the REST API so the upgrade request is
 * authenticated by the existing session cookie.
 */
export function setupRealtime(
  httpServer: Server,
  sessionMiddleware: RequestHandler,
): void {
  wss = new WebSocketServer({ noServer: true });

  httpServer.on("upgrade", (req, socket, head) => {
    let pathname = "";
    try {
      pathname = parseUrl(req.url || "").pathname || "";
    } catch {
      /* leave empty */
    }
    // Only handle our channel — let other upgrade listeners (e.g. Vite HMR in
    // dev) handle theirs. Returning without touching the socket is required so
    // we don't clobber another handler's upgrade.
    if (pathname !== "/ws") return;

    // Run the session middleware to populate req.session from the cookie.
    const stubRes = {
      on() {},
      once() {},
      end() {},
      setHeader() {},
      getHeader() {},
      writeHead() {},
      removeHeader() {},
    } as any;

    try {
      sessionMiddleware(req as any, stubRes, () => {
        const session = (req as any).session;
        const passportUser = session?.passport?.user;
        if (!passportUser) {
          try {
            socket.write("HTTP/1.1 401 Unauthorized\r\n\r\n");
          } catch {}
          socket.destroy();
          return;
        }
        wss!.handleUpgrade(req, socket, head, (ws) => {
          wss!.emit("connection", ws, req);
        });
      });
    } catch {
      try {
        socket.destroy();
      } catch {}
    }
  });

  wss.on("connection", (ws: WebSocket, req: IncomingMessage) => {
    let tenantId = "";
    try {
      tenantId = (parseUrl(req.url || "", true).query.tenantId as string) || "";
    } catch {
      /* ignore */
    }
    if (!tenantId) {
      tenantId = (req as any).session?.viewTenantId || "";
    }
    // Only accept well-formed tenant UUIDs so a malformed client can't spawn
    // junk channels in the registry.
    if (!tenantId || !UUID_RE.test(tenantId)) {
      try {
        ws.close(1008, "valid tenantId required");
      } catch {}
      return;
    }

    let set = tenants.get(tenantId);
    if (!set) {
      set = new Set();
      tenants.set(tenantId, set);
    }
    set.add(ws);

    (ws as any).isAlive = true;
    ws.on("pong", () => {
      (ws as any).isAlive = true;
    });
    ws.on("message", (data) => {
      // Cheap app-level heartbeat fallback for environments where ws.ping is
      // stripped by a proxy.
      try {
        if (String(data) === "ping") ws.send("pong");
      } catch {}
    });
    ws.on("close", () => {
      set!.delete(ws);
      if (set!.size === 0) tenants.delete(tenantId);
    });
    ws.on("error", () => {
      try {
        ws.close();
      } catch {}
    });

    try {
      ws.send(JSON.stringify({ type: "connected", tenantId }));
    } catch {}
  });

  // Keepalive: ping clients and reap dead sockets.
  setInterval(() => {
    tenants.forEach((set) => {
      set.forEach((ws) => {
        if ((ws as any).isAlive === false) {
          try {
            ws.terminate();
          } catch {}
          return;
        }
        (ws as any).isAlive = false;
        try {
          ws.ping();
        } catch {}
      });
    });
  }, KEEPALIVE_MS);
}
